---
- name: "Playbook for Apach install"
  hosts: f1-micro
  gather_facts: no

  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 900
    - name: httpd package install
      yum:
        name: httpd
        state: present

    - name: deploy index.html
      copy:
        src: ./index.html
        dest: /var/www/html/index.html

    - name: httpd service
      service:
        name: httpd
        state: started
        enabled: yes


        
