- name: Create an instance
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
      project_id: key-prism-252210
      service_account_file: ./my_account.json
      service_account_email: ansible@key-prism-252210.iam.gserviceaccount.com
      zone: "us-central1-a"

  tasks:
    - name: Create an instance
      gce:
        instance_names: "apache-server"
        machine_type: "f1-micro"
        image: "centos-7"
        zone: "{{ zone }}"
        disk_size: 64
        service_account_email: "{{service_account_email}}"
        credentials_file: "{{service_account_file}}"
        project_id: "{{ project_id }}"

      register: gce

    - name: Wait for ssh to come up
      local_action: wait_for host="{{ item.public_ip }}" port=22 delay=10  timeout=100
      with_items: gce.instance_data
